#!/usr/bin/env file .

# -*-  Coding: UTF-8  -*- #
# -*-  System: Linux  -*- #
# -*-  Usage:  *.Yaml -*- #

#
# ========================================================================
# --> Pipeline: Continuous Integration & Deployment Configuration(s)
# ========================================================================
#

.Tags: &Runner [ "Development" ]

# ------------------------------------------------------------------------
# Primary Entry-Point (Jobs + Stages + Triggers)
# ------------------------------------------------------------------------

variables:
    MODULE: "rest-api-gateway-lambda-function"
    PROVIDER: "aws"

include:
    -   project: "terraform/ci-cd"
        ref: "Development"
        file: "Terraform-Module-Upload.Yaml"

stages:
    - Package

Upload:
    stage: Package
    extends: .TF-Module
    variables:
        TERRAFORM_MODULE_NAME: "${MODULE}"
        TERRAFORM_MODULE_SYSTEM: "${PROVIDER}"
    rules:
        -   if: $CI_COMMIT_TAG

default:
    tags: *Runner
    image: registry.mycapstone.com/iron-works/node-js-alpine/development/lts
    retry: 2
    cache: [ ]
